title: Todd Takala's Portfolio
description: A place to share some of my engineering anddata science work.
show_downloads: false
google_analytics:
remote_theme: forloop11/markdown-cv
plugins:
  - jekyll-seo-tag